# Generated by Django 2.2.2 on 2019-08-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='direccion_viento',
            field=models.CharField(choices=[('ESTE', 'Este'), ('OESTE', 'Oeste'), ('NORTE', 'Norte'), ('SUR', 'Sur')], default='ESTE', max_length=10),
        ),
    ]
