# Generated by Django 2.2.4 on 2019-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190823_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='direccion_viento',
            field=models.CharField(choices=[('ESTE', 'Este'), ('OESTE', 'Oeste'), ('NORTE', 'Norte'), ('SUR', 'Sur'), ('NOR ESTE', 'Nor este'), ('NOR OESTE', 'Nor oeste'), ('SUR OESTE', 'Sur oeste'), ('SUR ESTE', 'Sur este')], default='ESTE', max_length=10),
        ),
    ]
